from __future__ import annotations

from datetime import date
from typing import Protocol

from .models import Email, Memory, Task


class InboxPort(Protocol):
    def unread_primary(self) -> list[Email]: ...
    def thread(self, thread_id: str) -> list[Email]: ...


class TaskPort(Protocol):
    def list_open(self) -> list[Task]: ...
    def create(self, task: Task) -> Task: ...
    def update(self, task: Task) -> Task: ...


class CalendarPort(Protocol):
    def is_available(self, day: date) -> bool: ...
    def conflicts_on(self, day: date) -> list[dict[str, str]]: ...


class SearchPort(Protocol):
    def news(self, interests: list[str]) -> list[dict[str, str]]: ...
    def activities(self, interests: list[str], start: date, end: date) -> list[dict[str, str]]: ...


class MemoryPort(Protocol):
    def add(self, memory: Memory) -> Memory: ...
    def search(self, query: str, limit: int = 5) -> list[Memory]: ...


class FeedbackPort(Protocol):
    def search_feedback(self, query: str, limit: int = 3) -> list[dict[str, object]]: ...


class AuditPort(Protocol):
    def record(self, event_type: str, details: dict[str, object]) -> None: ...
    def was_processed(self, source: str, item_id: str) -> bool: ...
    def mark_processed(self, source: str, item_id: str) -> None: ...
    def queue_approval(self, trigger: str, action: dict[str, object]) -> str: ...
